CREATE STREAM LAB_STM_DEMO_DROP_KSQL_OBJECT_0010
	WITH (KAFKA_TOPIC = 'dev.etl.datagen.orders.src.0010', VALUE_FORMAT = 'Avro');

CREATE STREAM LAB_STM_DEMO_DROP_KSQL_OBJECT_0020 AS

SELECT CUSTOMERID, AS_MAP(AS_ARRAY('orderID', 'StorePickUpFlag', 'ItemName', 'OrderDate'), AS_ARRAY(ORDERID, STOREPICKUPFLAG, ITEMNAME, ORDERDATE)) AS orderData
FROM LAB_STM_DEMO_DROP_KSQL_OBJECT_0010 PARTITION BY CUSTOMERID;

CREATE TABLE LAB_TBL_DEMO_DROP_KSQL_OBJECT_0030 AS

SELECT CUSTOMERID, COLLECT_LIST(CAST(ORDERDATA AS VARCHAR))
FROM LAB_STM_DEMO_DROP_KSQL_OBJECT_0020
GROUP BY CUSTOMERID EMIT CHANGES;
